# Generated by Django 6.0.6 on 2026-07-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AcuerdoPago',
            fields=[
                ('id_acuerdo_pago', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total_acuerdo_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('observaciones_acuerdo_pago', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'acuerdo_pago',
            },
        ),
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(max_length=100, unique=True)),
                ('descripcion_cargo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'cargo',
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.AutoField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'ciudad',
            },
        ),
        migrations.CreateModel(
            name='MotivoContrato',
            fields=[
                ('id_contrato', models.AutoField(primary_key=True, serialize=False)),
                ('motivo_contrato', models.CharField(max_length=200, unique=True)),
            ],
            options={
                'db_table': 'motivo_contrato',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
                ('descripcion_rol', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicio', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_servicio', models.CharField(max_length=150)),
                ('precio_minimo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('precio_maximo', models.DecimalField(decimal_places=2, max_digits=15)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'servicios',
            },
        ),
        migrations.CreateModel(
            name='FechasPago',
            fields=[
                ('id_fecha_pago', models.AutoField(primary_key=True, serialize=False)),
                ('valor_fecha_pago', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fecha_pago', models.DateField()),
                ('estado_pago', models.CharField(blank=True, max_length=25, null=True)),
                ('valor_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_pagado', models.DateField(blank=True, null=True)),
                ('id_acuerdo_pago', models.ForeignKey(db_column='id_acuerdo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.acuerdopago')),
            ],
            options={
                'db_table': 'fechas_pago',
            },
        ),
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id_lead', models.AutoField(primary_key=True, serialize=False)),
                ('estado_lead', models.CharField(default='NUEVO', max_length=20)),
                ('telefono_marcado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True)),
                ('hora_creacion', models.TimeField(auto_now_add=True, null=True)),
                ('id_acuerdo_pago', models.ForeignKey(blank=True, db_column='id_acuerdo_pago', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.acuerdopago')),
                ('id_contrato', models.ForeignKey(blank=True, db_column='id_contrato', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.motivocontrato')),
            ],
            options={
                'db_table': 'leads',
            },
        ),
        migrations.CreateModel(
            name='DocumentosLead',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_documento', models.CharField(choices=[('CEDULA', 'Documento de Identidad'), ('CONTRATO', 'Contrato Firmado'), ('REPORTE', 'Reporte de Crédito'), ('OTRO', 'Otro Documento')], max_length=50)),
                ('archivo', models.FileField(upload_to='documentos_clientes/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.CASCADE, to='leads.leads')),
            ],
            options={
                'db_table': 'documentos_lead',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id_persona', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('tipo_documento_persona', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_documento_persona', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('fecha_expedicion_persona', models.DateField(blank=True, null=True)),
                ('fecha_nacimiento_persona', models.DateField(blank=True, null=True)),
                ('genero_persona', models.CharField(blank=True, max_length=20, null=True)),
                ('correo_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_persona', models.CharField(blank=True, max_length=150, null=True)),
                ('complemento_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('barrio_persona', models.CharField(blank=True, max_length=100, null=True)),
                ('id_ciudad', models.ForeignKey(blank=True, db_column='id_ciudad', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.ciudad')),
            ],
            options={
                'db_table': 'persona',
            },
        ),
        migrations.AddField(
            model_name='leads',
            name='id_persona',
            field=models.ForeignKey(blank=True, db_column='id_persona', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.persona'),
        ),
        migrations.CreateModel(
            name='ReporteGrafico',
            fields=[
                ('id_reporte_grafico', models.AutoField(primary_key=True, serialize=False)),
                ('documento_reporte_grafico', models.FileField(blank=True, max_length=255, null=True, upload_to='reportes_plataformas/')),
                ('tipo_reporte_grafico', models.CharField(blank=True, max_length=50, null=True)),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads')),
            ],
            options={
                'db_table': 'reporte_grafico',
            },
        ),
        migrations.CreateModel(
            name='Sede',
            fields=[
                ('id_sede', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_sede', models.CharField(max_length=100)),
                ('direccion_sede', models.CharField(blank=True, max_length=150, null=True)),
                ('correo_sede', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_sede', models.CharField(blank=True, max_length=20, null=True)),
                ('id_responsable', models.ForeignKey(blank=True, db_column='id_responsable', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.persona')),
            ],
            options={
                'db_table': 'sede',
            },
        ),
        migrations.CreateModel(
            name='AcuerdoPagoDetalle',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('valor_cobrado', models.DecimalField(decimal_places=2, max_digits=15)),
                ('id_acuerdo_pago', models.ForeignKey(db_column='id_acuerdo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.acuerdopago')),
                ('id_servicio', models.ForeignKey(db_column='id_servicio', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.servicios')),
            ],
            options={
                'db_table': 'acuerdo_pago_detalle',
            },
        ),
        migrations.CreateModel(
            name='Telefonos',
            fields=[
                ('id_telefono', models.AutoField(primary_key=True, serialize=False)),
                ('numero_telefono', models.CharField(max_length=20)),
                ('tipo_telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.persona')),
            ],
            options={
                'db_table': 'telefonos',
            },
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id_trabajador', models.AutoField(primary_key=True, serialize=False)),
                ('id_cargo', models.ForeignKey(blank=True, db_column='id_cargo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.cargo')),
                ('id_persona', models.OneToOneField(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.persona')),
                ('id_sede', models.ForeignKey(blank=True, db_column='id_sede', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.sede')),
            ],
            options={
                'db_table': 'trabajador',
            },
        ),
        migrations.CreateModel(
            name='Observaciones',
            fields=[
                ('id_observaciones', models.AutoField(primary_key=True, serialize=False)),
                ('observacion', models.TextField()),
                ('motivo_finalizacion_llamada', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_llamada', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateTimeField(blank=True, null=True)),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads')),
                ('id_trabajador', models.ForeignKey(blank=True, db_column='id_trabajador', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leads.trabajador')),
            ],
            options={
                'db_table': 'observaciones',
            },
        ),
        migrations.AddField(
            model_name='leads',
            name='id_trabajador',
            field=models.ForeignKey(db_column='id_trabajador', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.trabajador'),
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password_hash', models.CharField(max_length=255)),
                ('estado_usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('id_persona', models.ForeignKey(db_column='id_persona', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.persona')),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.rol')),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='UsuarioReporte',
            fields=[
                ('id_reporte', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('password_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('plataforma_reporte', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion_reporte', models.TextField(blank=True, null=True)),
                ('id_lead', models.ForeignKey(db_column='id_lead', on_delete=django.db.models.deletion.DO_NOTHING, to='leads.leads')),
            ],
            options={
                'db_table': 'usuario_reporte',
            },
        ),
    ]
